[pytest]
addopts = -v -s --tb=short
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*

markers =
    smoke: smoke tests
    regression: full regression tests
    auth: authentication tests
    positive: positive test cases
    negative: negative test cases
    get: GET requests
    post: POST requests
    put: PUT requests
    patch: PATCH requests
    delete: DELETE requests